version: "3.9"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: .
    env_file:
      - projectread/settings/.env
    command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000 --settings=projectread.settings.local"
    volumes:
      - .:/code/
    ports:
      - "8000:8000"
    depends_on:
      - db
