version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.9
    working_directory: ~/projectread
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Test
          command: ./manage.py test
      - run:
          name: Lint
          command: black --check .
