# Generated by Django 3.1.6 on 2021-03-13 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [
        ("registration", "0005_auto_20210310_0120"),
        ("registration", "0006_auto_20210310_0151"),
        ("registration", "0007_auto_20210310_0152"),
    ]

    dependencies = [
        ("registration", "0004_childinfo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="family",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="registration.family",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="family",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="registration.family",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="family",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="students",
                to="registration.family",
            ),
        ),
    ]
