# Generated by Django 3.1.6 on 2021-03-06 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_childinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='childinfo',
            name='active',
        ),
        migrations.RemoveField(
            model_name='familyinfo',
            name='active',
        ),
    ]
