# Generated by Django 3.1.6 on 2021-03-07 05:10

from django.db import migrations, models
import django.db.models.deletion
import registration.validators


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0005_auto_20210306_2153"),
    ]

    operations = [
        migrations.AddField(
            model_name="family",
            name="parent",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="represents_family",
                to="registration.student",
                validators=[registration.validators.validate_family_parent],
            ),
        ),
    ]
