# Generated by Django 3.1.6 on 2021-03-20 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0007_auto_20210314_0223"),
    ]

    operations = [
        migrations.CreateModel(
            name="Field",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("Parent", "Parent"),
                            ("Child", "Child"),
                            ("Guest", "Guest"),
                        ],
                        max_length=6,
                    ),
                ),
                ("name", models.CharField(max_length=512)),
                ("question", models.CharField(max_length=512)),
                (
                    "question_type",
                    models.CharField(
                        choices=[
                            ("Text", "Text"),
                            ("Multiple Choice", "Multiple Choice"),
                        ],
                        max_length=15,
                    ),
                ),
                ("is_default", models.BooleanField()),
                ("order", models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name="ChildInfo",
        ),
        migrations.DeleteModel(
            name="FamilyInfo",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="attendee_type",
            new_name="role",
        ),
    ]
