# Generated by Django 3.1.6 on 2021-03-10 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0007_auto_20210310_0152'),
        ('registration', '0006_family_parent'),
    ]

    operations = [
    ]
