# Generated by Django 3.1.6 on 2021-03-21 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0008_auto_20210320_1833"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="information",
            field=models.JSONField(default=dict),
        ),
    ]
