# Generated by Django 3.1.6 on 2021-04-03 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0009_auto_20210321_1836"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="family",
            name="phone_number",
        ),
        migrations.AddField(
            model_name="family",
            name="cell_number",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="family",
            name="home_number",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
        migrations.AddField(
            model_name="family",
            name="preferred_number",
            field=models.CharField(
                choices=[("Home", "Home"), ("Cell", "Cell"), ("Work", "Work")],
                default="Cell",
                max_length=4,
            ),
        ),
        migrations.AddField(
            model_name="family",
            name="work_number",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
    ]
