# Generated by Django 3.1.6 on 2021-05-01 19:11

import django.contrib.postgres.fields
from django.db import migrations, models
import registration.validators


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0010_auto_20210403_2021"),
    ]

    operations = [
        migrations.AddField(
            model_name="field",
            name="options",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=64),
                blank=True,
                null=True,
                size=None,
                validators=[registration.validators.validate_mc_options],
            ),
        ),
    ]
