# Generated by Django 3.1.6 on 2021-05-22 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0010_auto_20210403_2021"),
    ]

    operations = [
        migrations.AddField(
            model_name="family",
            name="notes",
            field=models.TextField(blank=True),
        ),
    ]
