# Generated by Django 3.1.6 on 2021-05-30 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0011_student_date_of_birth"),
        ("registration", "0011_field_options"),
    ]

    operations = []
