# Generated by Django 3.1.6 on 2021-05-30 22:00

import django.contrib.postgres.fields
from django.db import migrations, models
import registration.validators


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0012_merge_20210530_2141"),
    ]

    operations = [
        migrations.AlterField(
            model_name="field",
            name="options",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=64),
                blank=True,
                default=list,
                size=None,
                validators=[registration.validators.validate_mc_options],
            ),
        ),
    ]
