# Generated by Django 3.1.6 on 2021-06-04 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0011_family_notes"),
        ("registration", "0013_auto_20210530_2200"),
    ]

    operations = []
