# Generated by Django 3.1.6 on 2021-06-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0013_auto_20210530_2200"),
    ]

    operations = [
        migrations.AddField(
            model_name="family",
            name="notes",
            field=models.TextField(blank=True),
        ),
    ]
