# Generated by Django 3.1.6 on 2021-07-25 14:27

from django.db import migrations, models
import registration.validators


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0014_family_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="family",
            name="interactions",
            field=models.JSONField(
                default=list, validators=[registration.validators.validate_interactions]
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
    ]
