# Generated by Django 3.1.6 on 2021-07-25 14:52

from django.db import migrations, models
import registration.validators


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0015_auto_20210716_1611"),
    ]

    operations = [
        migrations.AddField(
            model_name="family",
            name="interactions",
            field=models.JSONField(
                default=list, validators=[registration.validators.validate_interactions]
            ),
        ),
    ]
