# Generated by Django 3.1.6 on 2021-07-25 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0015_auto_20210716_1611"),
        ("registration", "0015_family_interactions"),
    ]

    operations = []
