# Generated by Django 3.1.6 on 2021-07-31 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0016_family_interactions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='role',
            field=models.CharField(choices=[('Parent', 'Parent'), ('Child', 'Child'), ('Guest', 'Guest'), ('Session', 'Session')], max_length=7),
        ),
    ]
