# Generated by Django 3.1.6 on 2021-08-24 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0021_auto_20210823_2358"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="last_name",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
    ]
