# Generated by Django 3.1.6 on 2021-02-17 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrolments", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "season",
                    models.CharField(
                        choices=[
                            ("Spring", "Spring"),
                            ("Summer", "Summer"),
                            ("Fall", "Fall"),
                        ],
                        max_length=6,
                    ),
                ),
                ("year", models.PositiveSmallIntegerField()),
            ],
        ),
    ]
