# Generated by Django 3.1.6 on 2021-02-27 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrolments", "0004_enrolment"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="attendance",
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
    ]
