# Generated by Django 3.1.6 on 2021-02-27 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enrolments', '0004_enrolment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='enrolments.session'),
        ),
    ]
