# Generated by Django 3.1.6 on 2021-03-13 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("enrolments", "0004_enrolment"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrolment",
            name="preferred_class",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="preferred_enrolment",
                to="enrolments.class",
            ),
        ),
        migrations.AddField(
            model_name="enrolment",
            name="session",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="enrolments.session",
            ),
        ),
    ]
