# Generated by Django 3.1.6 on 2021-03-06 20:18

from django.db import migrations, models
import enrolments.validators


class Migration(migrations.Migration):

    dependencies = [
        ("enrolments", "0004_enrolment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="class",
            options={"verbose_name_plural": "classes"},
        ),
        migrations.AddField(
            model_name="class",
            name="attendance",
            field=models.JSONField(
                validators=[enrolments.validators.validate_attendance]
            ),
        ),
    ]
