# Generated by Django 3.1.6 on 2021-03-13 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("enrolments", "0005_auto_20210227_2135"),
        ("enrolments", "0005_auto_20210313_2013"),
    ]

    operations = []
