# Generated by Django 3.1.6 on 2021-03-20 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("enrolments", "0005_auto_20210306_2018"),
        ("enrolments", "0006_merge_20210313_2035"),
    ]

    operations = []
