# Generated by Django 3.1.6 on 2021-04-03 20:16

import django.contrib.postgres.fields
from django.db import migrations, models
import enrolments.validators


class Migration(migrations.Migration):

    dependencies = [
        ("enrolments", "0007_merge_20210320_1853"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrolment",
            name="students",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveIntegerField(),
                default=list,
                size=None,
                validators=[enrolments.validators.validate_student_ids_in_family],
            ),
        ),
    ]
