# Generated by Django 3.1.6 on 2021-04-20 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("enrolments", "0008_enrolment_students"),
        ("enrolments", "0008_session_fields"),
    ]

    operations = []
