# Generated by Django 3.1.6 on 2021-04-28 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("enrolments", "0009_enrolment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrolment",
            name="enrolled_class",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="enrolments",
                to="enrolments.class",
            ),
        ),
        migrations.AlterField(
            model_name="enrolment",
            name="preferred_class",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="enrolments.class",
            ),
        ),
        migrations.AlterField(
            model_name="enrolment",
            name="session",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="enrolments",
                to="enrolments.session",
            ),
        ),
    ]
