# Generated by Django 3.1.6 on 2021-05-02 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("enrolments", "0009_merge_20210420_2254"),
        ("enrolments", "0010_auto_20210428_0248"),
    ]

    operations = []
