# Generated by Django 3.1.6 on 2021-05-22 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enrolments', '0012_session_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolment',
            name='enrolled_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrolments', to='enrolments.class'),
        ),
    ]
