# Generated by Django 3.1.6 on 2021-05-29 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0011_family_notes"),
        ("enrolments", "0013_auto_20210522_1859"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrolment",
            name="enrolled_class",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="enrolments",
                to="enrolments.class",
            ),
        ),
        migrations.AlterField(
            model_name="enrolment",
            name="family",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="enrolments",
                to="registration.family",
            ),
        ),
        migrations.AlterField(
            model_name="session",
            name="start_date",
            field=models.DateField(null=True),
        ),
    ]
