# Generated by Django 3.1.6 on 2021-06-28 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrolments", "0014_auto_20210611_0334"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrolment",
            name="status",
            field=models.CharField(
                choices=[
                    ("Signed up", "Signed up"),
                    ("Registered", "Registered"),
                    ("Class allocated", "Class allocated"),
                    ("Completed", "Completed"),
                    ("No show", "No show"),
                    ("Drop out", "Drop out"),
                    ("Waitlisted", "Waitlisted"),
                ],
                default="Signed up",
                max_length=16,
            ),
        ),
    ]
