# Generated by Django 3.1.6 on 2021-07-13 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enrolments', '0015_auto_20210628_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolment',
            name='preferred_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='enrolments.class'),
        ),
    ]
