# Generated by Django 3.1.6 on 2021-07-28 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrolments", "0016_auto_20210713_2155"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="session",
            name="season",
        ),
        migrations.RemoveField(
            model_name="session",
            name="year",
        ),
        migrations.AddField(
            model_name="session",
            name="name",
            field=models.CharField(default="", max_length=128),
        ),
    ]
