# Generated by Django 3.1.6 on 2021-07-29 04:49

import django.contrib.postgres.fields
from django.db import migrations, models
import enrolments.validators


class Migration(migrations.Migration):

    dependencies = [
        ("enrolments", "0017_auto_20210728_0442"),
    ]

    operations = [
        migrations.AlterField(
            model_name="class",
            name="attendance",
            field=models.JSONField(
                blank=True,
                default=list,
                validators=[enrolments.validators.validate_attendance],
            ),
        ),
        migrations.AlterField(
            model_name="enrolment",
            name="students",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.PositiveIntegerField(), default=list, size=None
            ),
        ),
    ]
