# Generated by Django 3.1.6 on 2021-08-13 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrolments", "0019_class_colour"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrolment",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
