# Generated by Django 3.1.6 on 2021-08-18 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrolments", "0020_auto_20210813_0252"),
    ]

    operations = [
        migrations.AddField(
            model_name="class",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="class",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name="session",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="session",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
