# Generated by Django 3.1.6 on 2021-08-20 22:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrolments", "0021_auto_20210818_0347"),
    ]

    operations = [
        migrations.AddField(
            model_name="class",
            name="days",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    blank=True,
                    choices=[
                        ("Monday", "Monday"),
                        ("Tuesday", "Tuesday"),
                        ("Wednesday", "Wednesday"),
                        ("Thursday", "Thursday"),
                        ("Friday", "Friday"),
                        ("Saturday", "Saturday"),
                        ("Sunday", "Sunday"),
                    ],
                    max_length=9,
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="class",
            name="location",
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
