# Generated by Django 3.1.6 on 2021-08-21 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrolments", "0022_auto_20210820_2246"),
    ]

    operations = [
        migrations.AddField(
            model_name="session",
            name="active",
            field=models.BooleanField(default=False),
        ),
    ]
