# Generated by Django 3.1.6 on 2021-09-23 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enrolments", "0023_session_active"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="enrolment",
            name="active",
        ),
        migrations.AddField(
            model_name="enrolment",
            name="is_guest",
            field=models.BooleanField(default=False),
        ),
    ]
